# Generated by Django 4.0.1 on 2022-01-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ad', '0002_adobjecttype_areadetail_ad_ad_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
