# Generated by Django 4.0.1 on 2022-01-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_ad_content_type_alter_ad_object_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdObjectType',
            new_name='AdDetailType',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='ad_object_type',
            new_name='ad_detail_type',
        ),
    ]
