# Generated by Django 4.0.1 on 2022-01-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_adimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adimage',
            old_name='path',
            new_name='image',
        ),
    ]
