# Generated by Django 4.0.1 on 2022-01-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_rename_path_adimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикаций'},
        ),
        migrations.AlterModelOptions(
            name='addetailtype',
            options={'verbose_name': 'Тип детальной информаций', 'verbose_name_plural': 'Тип детальной информаций'},
        ),
        migrations.AlterModelOptions(
            name='adimage',
            options={'verbose_name': 'Фотография для Публикаций', 'verbose_name_plural': 'Фотографий для Публикаций'},
        ),
        migrations.AlterModelOptions(
            name='adtype',
            options={'verbose_name': 'Тип публикаций', 'verbose_name_plural': 'Типы публикаций'},
        ),
        migrations.AlterModelOptions(
            name='areadetail',
            options={'verbose_name': 'Участок дополнение публикаций', 'verbose_name_plural': 'Участок дополнение публикаций'},
        ),
        migrations.AlterModelOptions(
            name='buildingtype',
            options={'verbose_name': 'Тип построение', 'verbose_name_plural': 'Тип построение'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='homedetail',
            options={'verbose_name': 'Дом дополнение публикаций', 'verbose_name_plural': 'Дом дополнение публикаций'},
        ),
        migrations.AlterModelOptions(
            name='renttype',
            options={'verbose_name': 'Время аренды', 'verbose_name_plural': 'Время аренды'},
        ),
        migrations.AlterModelOptions(
            name='repairtype',
            options={'verbose_name': 'Тип ремонта', 'verbose_name_plural': 'Типы ремонта'},
        ),
        migrations.AddField(
            model_name='addetailtype',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
