# Generated by Django 4.0.1 on 2022-02-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_communications_rename_area_areadetail_total_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
