# Generated by Django 4.0.1 on 2022-02-03 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad', '0012_adlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adlike',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ad.ad'),
        ),
        migrations.AlterField(
            model_name='adlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='adlike',
            constraint=models.UniqueConstraint(fields=('user', 'ad'), name='unique_like'),
        ),
    ]
