# Generated by Django 4.0.1 on 2022-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_adlike_created_at_alter_adlike_ad_alter_adlike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlike',
            name='isLiked',
            field=models.BooleanField(default=True),
        ),
    ]
