# Generated by Django 4.0.1 on 2022-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0016_alter_areadetail_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcomments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
