# Generated by Django 4.0.1 on 2022-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0019_ad_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
