# Generated by Django 4.0.1 on 2022-02-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
