# Generated by Django 4.0.1 on 2022-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
