# Generated by Django 4.0.1 on 2022-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_about_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
