# Generated by Django 4.0.1 on 2022-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_notifcationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ball',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
