# Generated by Django 4.0.1 on 2022-02-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_rating_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
