# Generated by Django 4.0.1 on 2022-02-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_notification_is_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ball',
            field=models.FloatField(blank=True, default=3, null=True),
        ),
    ]
